{
 "title": "proc_interrupts_metrics_ref",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   {
    "name": "devices",
    "label": "Devices",
    "query": {
     "query": "proc_interrupts_info{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "dev_irq",
    "label": "Dev IRQ",
    "query": {
     "query": "proc_interrupts_info{instance=~\"${instance}\",hostname=~\"${hostname}\",dev=~\"${devices}\"}"
    }
   },
   {
    "name": "non_dev_irq",
    "label": "Non Dev IRQ",
    "query": {
     "query": "proc_interrupts_info{instance=~\"${instance}\",hostname=~\"${hostname}\",dev=\"\"}"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "proc_interrupts_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",irq=\"0\"}"
    }
   },
   { "name": "interval", "query": "1s" },
   { "name": "lookback", "query": "16s" },
   { "name": "threshold", "label": "Delta Threshold", "query": "0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**NOTES:** \n\n1. See [LSVMI Interrupts Metrics](https://github.com/emypar/linux-stats-victoriametrics-importer/blob/main/docs/proc_interrupts_metrics.md) for metrics description.\n1. All panels requires specifc `instance` and `hostname`\n"
   }
  },
  {
   "title": "Dev Interrupts# Delta For ${instance}/${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "proc_interrupts_delta{\n    instance=\"${instance}\",\n    hostname=\"${hostname}\",\n    irq=~\"${dev_irq}\",\n    dev=~\"${devices}\",\n    cpu=~\"${cpu}\"\n} >= ${threshold}",
     "legendFormat": "IRQ{{irq}}(dev={{dev}}, cpu={{cpu}}, host={{hostname}},inst={{instance}})"
    }
   ]
  },
  {
   "title": "Dev Interrupts Rate For ${instance}/${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "(\n    proc_interrupts_delta{\n        instance=\"${instance}\",\n        hostname=\"${hostname}\",\n        irq=~\"${dev_irq}\",\n        dev=~\"${devices}\",\n        cpu=~\"${cpu}\"\n    } >= ${threshold}\n) \n/ on (instance, hostname) group_left\nproc_interrupts_metrics_delta_sec{\n    instance=\"${instance}\",\n    hostname=\"${hostname}\"\n}",
     "legendFormat": "IRQ{{irq}}(dev={{dev}}, cpu={{cpu}}, host={{hostname}},inst={{instance}})"
    }
   ]
  },
  {
   "title": "Non Dev Interrupts# Delta For ${instance}/${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "proc_interrupts_delta{\n    instance=\"${instance}\", \n    hostname=\"${hostname}\", \n    irq=~\"${non_dev_irq}\", \n    dev=\"\", \n    cpu=~\"${cpu}\"\n} >= ${threshold}",
     "legendFormat": "IRQ{{irq}}(dev={{dev}}, cpu={{cpu}}, host={{hostname}},inst={{instance}})"
    }
   ]
  },
  {
   "title": "Non Dev Interrupts Rate For ${instance}/${hostname}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "(\n    proc_interrupts_delta{\n        instance=\"${instance}\",\n        hostname=\"${hostname}\",\n        irq=~\"${non_dev_irq}\",\n        dev=\"\",\n        cpu=~\"${cpu}\"\n    } >= ${threshold}\n)\n/ on (instance, hostname) group_left\nproc_interrupts_metrics_delta_sec{\n    instance=\"${instance}\",\n    hostname=\"${hostname}\"\n}",
     "legendFormat": "IRQ{{irq}}(dev={{dev}}, cpu={{cpu}}, host={{hostname}},inst={{instance}})"
    }
   ]
  }
 ]
}