{
 "title": "proc_pid_metrics_ref",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   {
    "name": "comm",
    "label": "Comm",
    "query": {
     "query": "proc_pid_stat_comm{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "pid",
    "label": "PID",
    "query": {
     "query": "proc_pid_stat_comm{instance=\"${instance}\",hostname=\"${hostname}\",comm=\"${comm}\"}"
    }
   },
   {
    "name": "threads",
    "label": "Threads",
    "query": "On : \".*\", Off : \"\", Only : \".+\""
   },
   {
    "name": "part",
    "label": "Partition",
    "query": {
     "query": "proc_pid_metrics_delta_sec{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   { "name": "interval", "query": "1s" },
   { "name": "lookback_interval", "query": "5" },
   { "name": "full_cycle_interval", "query": "15" }
  ]
 },
 "panels": [
  {
   "title": "Host Centric Top View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "* requires specific `Instance` and `Hostname`\n* supports additional filtering via `Comm`\n* it displays only processes that were active in the last ${lookback_interval} sec (`lookback_interval` variable)\n* `%CPU` column is the latest value\n* `%Max` and `%Avg` are computed over the last ${lookback_interval} sec (`lookback_interval` variable)"
     }
    },
    {
     "title": "Top View For Instance=${instance}, Hostname=${hostname}, Comm=${comm}",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "(\n    proc_pid_stat_state{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"} > 0\n) * on (instance, hostname, pid) group_right(state) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=~\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n) and on (instance, hostname, pid) (\n    sum_over_time(proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}[$lookback_interval]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=~\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n) and on (instance, hostname, pid) (\n    sum_over_time(proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}[$lookback_interval]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_cpu_num{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=~\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n) and on (instance, hostname, pid) (\n    sum_over_time(proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}[$lookback_interval]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_rss_bytes{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=~\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n) and on (instance, hostname, pid) (\n    sum_over_time(proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}[$lookback_interval]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max_over_time(proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}[${lookback_interval}])\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=~\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n) and on (instance, hostname, pid) (\n    sum_over_time(proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}[$lookback_interval]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    (\n        sum_over_time(proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}[${lookback_interval}]) > 0 \n    ) / ${lookback_interval}\n) * on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=~\"${comm}\", tid=\"\"}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    proc_pid_cmdline{instance=\"${instance}\", hostname=\"${hostname}\"} > 0\n) * on (instance, hostname, pid) group_right(cmd, args) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=~\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n) and on (instance, hostname, pid) (\n    sum_over_time(proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}[$lookback_interval]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_num_threads{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=~\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n) and on (instance, hostname, pid) (\n    sum_over_time(proc_pid_stat_pcpu{instance=\"${instance}\", hostname=\"${hostname}\", tid=\"\"}[$lookback_interval]) > 0\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Comm Centric Top View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "* requires specific `Comm` \n* supports additional filtering via `Instance` and `Hostname`\n* `%CPU` column is the latest value\n* `%Max` and `%Avg` are computed over the last ${lookback_interval} sec (`lookback_interval` variable)"
     }
    },
    {
     "title": "Top View For Comm=${comm},  Instance=${instance}, Hostname=${hostname}",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "(\n    proc_pid_stat_state{instance=~\"${instance}\", hostname=~\"${hostname}\", tid=\"\"} > 0\n) * on (instance, hostname, pid) group_right(state) (\n    last_over_time(proc_pid_stat_comm{instance=~\"${instance}\", hostname=~\"${hostname}\", comm=\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_pcpu{instance=~\"${instance}\", hostname=~\"${hostname}\", tid=\"\"}\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=~\"${instance}\", hostname=~\"${hostname}\", comm=\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_cpu_num{instance=~\"${instance}\", hostname=~\"${hostname}\", tid=\"\"}\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=~\"${instance}\", hostname=~\"${hostname}\", comm=\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_rss_bytes{instance=~\"${instance}\", hostname=~\"${hostname}\", tid=\"\"}\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=~\"${instance}\", hostname=~\"${hostname}\", comm=\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max_over_time(proc_pid_stat_pcpu{instance=~\"${instance}\", hostname=~\"${hostname}\", tid=\"\"}[${lookback_interval}])\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=~\"${instance}\", hostname=~\"${hostname}\", comm=\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    (\n        sum_over_time(proc_pid_stat_pcpu{instance=~\"${instance}\", hostname=~\"${hostname}\", tid=\"\"}[${lookback_interval}]) \n    ) / ${lookback_interval}\n) * on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=~\"${instance}\", hostname=~\"${hostname}\", comm=\"${comm}\", tid=\"\"}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\"} > 0\n) * on (instance, hostname, pid) group_right(cmd, args) (\n    last_over_time(proc_pid_stat_comm{instance=~\"${instance}\", hostname=~\"${hostname}\", comm=\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_num_threads{instance=~\"${instance}\", hostname=~\"${hostname}\", tid=\"\"}\n* on (instance, hostname, pid) (\n    last_over_time(proc_pid_stat_comm{instance=~\"${instance}\", hostname=~\"${hostname}\", comm=\"${comm}\",tid=\"\"}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Explorer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "* requires specific `Instance`, `Hostname` and `Comm`\n* supports additional filtering via `PID` and `Threads`\n"
     }
    },
    {
     "title": "Process Info For Instance=${instance}, Hostname=${hostname}, Comm=${comm}, PID=${pid}",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "(last_over_time(proc_pid_stat_info{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\"}[${full_cycle_interval}]) > 0)\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\",  pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(last_over_time(proc_pid_status_info{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\"}[${full_cycle_interval}]) > 0)\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\",  pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Priority For Instance=${instance}, Hostname=${hostname}, Comm=${comm}, PID=${pid}",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "(last_over_time(proc_pid_stat_prio{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\", tid=~${threads}}[${full_cycle_interval}]) > 0)\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\",  pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "%CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_pid_stat_pcpu{instance=\"${instance}\",hostname=\"${hostname}\", pid=~\"${pid}\", tid=~${threads}}\n* on (instance, hostname, pid, tid) group_left(comm) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=~${threads}}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "{{comm}}(pid={{pid}},tid={{tid}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "% Sytem CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_pid_stat_stime_pcpu{instance=\"${instance}\",hostname=\"${hostname}\", pid=~\"${pid}\", tid=~${threads}}\n* on (instance, hostname, pid, tid) group_left(comm) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=~${threads}}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "{{comm}}(pid={{pid}},tid={{tid}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "% User CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_pid_stat_utime_pcpu{instance=\"${instance}\",hostname=\"${hostname}\", pid=~\"${pid}\", tid=~${threads}}\n* on (instance, hostname, pid, tid) group_left(comm) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=~${threads}}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "{{comm}}(pid={{pid}},tid={{tid}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "%VSZ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "proc_pid_stat_vsize_bytes{instance=\"${instance}\",hostname=\"${hostname}\", pid=~\"${pid}\", tid=~${threads}}\n* on (instance, hostname, pid, tid) group_left(comm) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=~${threads}}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "{{comm}}(pid={{pid}},tid={{tid}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "%RSS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "proc_pid_stat_rss_bytes{instance=\"${instance}\",hostname=\"${hostname}\", pid=~\"${pid}\", tid=~${threads}}\n* on (instance, hostname, pid, tid) group_left(comm) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=~${threads}}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "{{comm}}(pid={{pid}},tid={{tid}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "VM Data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "proc_pid_status_vm_data{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\"}\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "{{comm}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "VM Exe",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "proc_pid_status_vm_exe{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\"}\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "{{comm}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "VM Stack",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "proc_pid_status_vm_stk{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\", tid=~${threads}}\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "{{comm}}(pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "VM Swap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "proc_pid_status_vm_swap{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\"}\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "{{comm}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "RSS Anon",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "proc_pid_status_rss_anon{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\"}\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "{{comm}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "RSS File",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "proc_pid_status_rss_file{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\"}\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "{{comm}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "RSS Shared Mem",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "proc_pid_status_rss_shmem{instance=\"${instance}\", hostname=\"${hostname}\", pid=~\"${pid}\"}\n* on (instance, hostname, pid) group_left(comm)\n(last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=\"\"}[${full_cycle_interval}]) > 0)",
       "legendFormat": "{{comm}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Min/Maj Flt# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_pid_stat_minflt_delta{instance=\"${instance}\",hostname=\"${hostname}\", pid=~\"${pid}\", tid=~${threads}}\n* on (instance, hostname, pid, tid) group_left(comm) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=~${threads}}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "minflt_delta({{comm}},pid={{pid}},tid={{tid}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "proc_pid_stat_majflt_delta{instance=\"${instance}\",hostname=\"${hostname}\", pid=~\"${pid}\", tid=~${threads}}\n* on (instance, hostname, pid, tid) group_left(comm) (\n    last_over_time(proc_pid_stat_comm{instance=\"${instance}\", hostname=\"${hostname}\", comm=\"${comm}\", pid=~\"${pid}\", tid=~${threads}}[${full_cycle_interval}]) > 0\n)",
       "legendFormat": "majflt_delta({{comm}},pid={{pid}},tid={{tid}},host={{hostname}},inst={{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "PID Counts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "{__name__=~\"proc_pid_.*_count\",instance=~\"${instance}\",hostname=~\"${hostname}\",part=~\"${part}\"}",
       "legendFormat": "{{__name__}}(part={{part}},host={{hostname}},inst={{instance}})"
      }
     ]
    }
   ]
  }
 ]
}