{
 "title": "proc_diskstats_metrics_ref",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   { "name": "mounted_only", "label": "Mounted Only", "query": "Yes : 1, No : 0" },
   {
    "name": "maj_min",
    "label": "Maj:Min",
    "query": {
     "query": "proc_diskstats_info{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "disk_name",
    "label": "DiskName",
    "query": {
     "query": "proc_diskstats_info{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "mount_point",
    "label": "Mount Point",
    "query": {
     "query": "proc_mountinfo{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   { "name": "interval", "query": "5s" },
   { "name": "lookback", "query": "65s" },
   { "name": "delta_threshold", "label": "Delta Threshold", "query": "0" },
   { "name": "rate_threshold", "label": "Rate Threshold", "query": "0" },
   { "name": "pct_threshold", "label": "% Threshold", "query": "0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**NOTES:** \n\n1. See [LSVMI Disk Stats And Mount Info Metrics](https://github.com/emypar/linux-stats-victoriametrics-importer/blob/main/docs/proc_diskstats_metrics.md) for metrics description.\n1. All panels requires specifc `instance` and `hostname`\n"
   }
  },
  {
   "title": "Mount Info For ${instance}/${hostname}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mount Info For ${instance}/${hostname} (Mounted Only = ${mounted_only})",
     "type": "table",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "last_over_time(\n  proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]\n)\n* on (instance, hostname, maj_min) group_left(mount_point, source, fs_type)\nlast_over_time(\n  proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]\n) > 0\nor on (instance, hostname, maj_min)\nlast_over_time(\n  proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]\n) * (1 - ${mounted_only}) > 0\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Deltas And Rates For ${instance}/${hostname}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Deltas For ${instance}/${hostname}, MntOnly: ${mounted_only}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "proc_diskstats_num_reads_completed_delta{\n  instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "completed(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "proc_diskstats_num_reads_merged_delta{\n  instance=~\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "merged(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "proc_diskstats_num_read_sectors_delta{\n  instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "sectors(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Read Rates For ${instance}/${hostname}, MntOnly: ${mounted_only}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
     "targets": [
      {
       "expr": "(\n  proc_diskstats_num_reads_completed_delta{\n    instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "completed(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "(\n  proc_diskstats_num_reads_merged_delta{\n    instance=~\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "merged(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "(\n  proc_diskstats_num_read_sectors_delta{\n    instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "sectors(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Write Deltas For ${instance}/${hostname}, MntOnly: ${mounted_only}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "proc_diskstats_num_writes_completed_delta{\n  instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "completed(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "proc_diskstats_num_writes_merged_delta{\n  instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "merged(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "proc_diskstats_num_write_sectors_delta{\n  instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "sectors(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Write Rates For ${instance}/${hostname}, MntOnly: ${mounted_only}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 14 },
     "targets": [
      {
       "expr": "(\n  proc_diskstats_num_writes_completed_delta{\n    instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=~\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "completed(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "(\n  proc_diskstats_num_writes_merged_delta{\n    instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=~\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "merged(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "(\n  proc_diskstats_num_write_sectors_delta{\n    instance=~\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=~\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "sectors(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Discard Deltas For ${instance}/${hostname}, MntOnly: ${mounted_only}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "proc_diskstats_num_discards_completed_delta{\n  instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "completed(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "proc_diskstats_num_discards_merged_delta{\n  instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "merged(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "proc_diskstats_num_discard_sectors_delta{\n  instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "sectors(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Discard Rates For ${instance}/${hostname}, MntOnly: ${mounted_only}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 22 },
     "targets": [
      {
       "expr": "(\n  proc_diskstats_num_discards_completed_delta{\n    instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "completed(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "(\n  proc_diskstats_num_discards_merged_delta{\n    instance=~\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=~\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "merged(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "(\n  proc_diskstats_num_discard_sectors_delta{\n    instance=~\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "sectors(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Flush Rq Deltas For ${instance}/${hostname}, MntOnly: ${mounted_only}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "proc_diskstats_num_flush_requests_delta{\n  instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${delta_threshold}\nand on (instance, hostname, maj_min)\n(\n  last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n  or\n  last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n) > 0",
       "legendFormat": "flush(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Flush Rq Rates For ${instance}/${hostname}, MntOnly: ${mounted_only}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 30 },
     "targets": [
      {
       "expr": "(\n  proc_diskstats_num_flush_requests_delta{\n    instance=\"${instance}\",hostname=\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n  }\n  and on (instance, hostname, maj_min)\n  (\n    last_over_time(proc_mountinfo{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * ${mounted_only}\n    or\n    last_over_time(proc_diskstats_info{instance=\"${instance}\",hostname=\"${hostname}\"}[${lookback}]) * (1 - ${mounted_only})\n  ) > 0\n) / on (instance, host) group_left()\n(\n  proc_diskstats_metrics_delta_sec{instance=\"${instance}\",hostname=\"${hostname}\"} > 0\n) >= ${rate_threshold}",
       "legendFormat": "flush(dev={{name}},maj_min={{maj_min}},host={{hostname}},inst={{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Percentage Time For Disk ${disk_name} On  ${instance}/${hostname}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Time For ${disk_name} On ${instance}/${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_diskstats_read_pct{instance=\"${instance}\",hostname=\"${hostname}\",name=\"${disk_name}\"}",
       "legendFormat": "read"
      },
      {
       "expr": "proc_diskstats_write_pct{instance=\"${instance}\",hostname=\"${hostname}\",name=\"${disk_name}\"}",
       "legendFormat": "write"
      },
      {
       "expr": "proc_diskstats_io_pct{instance=\"${instance}\",hostname=\"${hostname}\",name=\"${disk_name}\"}",
       "legendFormat": "io"
      },
      {
       "expr": "proc_diskstats_discard_pct{instance=\"${instance}\",hostname=\"${hostname}\",name=\"${disk_name}\"}",
       "legendFormat": "discard"
      },
      {
       "expr": "proc_diskstats_flush_pct{instance=\"${instance}\",hostname=\"${hostname}\",name=\"${disk_name}\"}",
       "legendFormat": "flush"
      }
     ]
    }
   ]
  }
 ]
}