{
 "title": "qdisc_metrics_ref",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   {
    "name": "if",
    "label": "IF",
    "query": {
     "query": "qdisc_present{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": {
     "query": "qdisc_present{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "handle",
    "label": "Handle",
    "query": {
     "query": "qdisc_present{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "parent",
    "label": "Parent",
    "query": {
     "query": "qdisc_present{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   { "name": "interval", "query": "1s" },
   { "name": "lookback", "query": "15s" }
  ]
 },
 "panels": [
  {
   "title": "Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "qdisc_rate_kbps{\n    instance=~\"${instance}\",hostname=~\"${hostname}\",\n    kind=~\"${kind}\",handle=~\"${handle}\",parent=~\"${parent}\",if=~\"${if}\",\n}",
       "legendFormat": "qdisc(if={{if}},handle={{handle}},kind={{kind}},parent={{parent}}) on {{hostname}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deltas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drops Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "qdisc_drops_delta{\n    instance=~\"${instance}\",hostname=~\"${hostname}\",\n    kind=~\"${kind}\",handle=~\"${handle}\",parent=~\"${parent}\",if=~\"${if}\",\n}",
       "legendFormat": "qdisc(if={{if}},handle={{handle}},kind={{kind}},parent={{parent}}) on {{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Pkts Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "qdisc_packets_delta{\n    instance=~\"${instance}\",hostname=~\"${hostname}\",\n    kind=~\"${kind}\",handle=~\"${handle}\",parent=~\"${parent}\",if=~\"${if}\",\n}",
       "legendFormat": "qdisc(if={{if}},handle={{handle}},kind={{kind}},parent={{parent}}) on {{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Overlimits Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "qdisc_overlimits_delta{\n    instance=~\"${instance}\",hostname=~\"${hostname}\",\n    kind=~\"${kind}\",handle=~\"${handle}\",parent=~\"${parent}\",if=~\"${if}\",\n}",
       "legendFormat": "qdisc(if={{if}},handle={{handle}},kind={{kind}},parent={{parent}}) on {{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Requeues Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "qdisc_requeues_delta{\n    instance=~\"${instance}\",hostname=~\"${hostname}\",\n    kind=~\"${kind}\",handle=~\"${handle}\",parent=~\"${parent}\",if=~\"${if}\",\n}",
       "legendFormat": "qdisc(if={{if}},handle={{handle}},kind={{kind}},parent={{parent}}) on {{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Throttled Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "qdisc_throttled_delta{\n    instance=~\"${instance}\",hostname=~\"${hostname}\",\n    kind=~\"${kind}\",handle=~\"${handle}\",parent=~\"${parent}\",if=~\"${if}\",\n}",
       "legendFormat": "qdisc(if={{if}},handle={{handle}},kind={{kind}},parent={{parent}}) on {{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Flows Limit Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "qdisc_flowsplimit_delta{\n    instance=~\"${instance}\",hostname=~\"${hostname}\",\n    kind=~\"${kind}\",handle=~\"${handle}\",parent=~\"${parent}\",if=~\"${if}\",\n}",
       "legendFormat": "qdisc(if={{if}},handle={{handle}},kind={{kind}},parent={{parent}}) on {{hostname}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "QLen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "qdisc_qlen{\n    instance=~\"${instance}\",hostname=~\"${hostname}\",\n    kind=~\"${kind}\",handle=~\"${handle}\",parent=~\"${parent}\",if=~\"${if}\",\n}",
       "legendFormat": "qdisc(if={{if}},handle={{handle}},kind={{kind}},parent={{parent}}) on {{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Backlog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "qdisc_backlog{\n    instance=~\"${instance}\",hostname=~\"${hostname}\",\n    kind=~\"${kind}\",handle=~\"${handle}\",parent=~\"${parent}\",if=~\"${if}\",\n}",
       "legendFormat": "qdisc(if={{if}},handle={{handle}},kind={{kind}},parent={{parent}}) on {{hostname}}/{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}