#! /usr/bin/env python3

# Generate test cases for lsvmi/proc_net_snmp_metrics_test.go

from typing import List

import procfs

DEFAULT_PROC_NET_DEV_INTERVAL_SEC = 1
DEFAULT_PROC_NET_DEV_FULL_METRICS_FACTOR = 15

ZeroDelta = List[bool]

# Metrics definitions, must match lsvmi/proc_net_snmp_metrics.go:
PROC_NET_SNMP_IP_FORWARDING_METRIC = "proc_net_snmp_ip_forwarding"
PROC_NET_SNMP_IP_DEFAULT_TTL_METRIC = "proc_net_snmp_ip_default_ttl"
PROC_NET_SNMP_IP_IN_RECEIVES_DELTA_METRIC = "proc_net_snmp_ip_in_receives_delta"
PROC_NET_SNMP_IP_IN_HDR_ERRORS_DELTA_METRIC = "proc_net_snmp_ip_in_hdr_errors_delta"
PROC_NET_SNMP_IP_IN_ADDR_ERRORS_DELTA_METRIC = "proc_net_snmp_ip_in_addr_errors_delta"
PROC_NET_SNMP_IP_FORW_DATAGRAMS_DELTA_METRIC = "proc_net_snmp_ip_forw_datagrams_delta"
PROC_NET_SNMP_IP_IN_UNKNOWN_PROTOS_DELTA_METRIC = (
    "proc_net_snmp_ip_in_unknown_protos_delta"
)
PROC_NET_SNMP_IP_IN_DISCARDS_DELTA_METRIC = "proc_net_snmp_ip_in_discards_delta"
PROC_NET_SNMP_IP_IN_DELIVERS_DELTA_METRIC = "proc_net_snmp_ip_in_delivers_delta"
PROC_NET_SNMP_IP_OUT_REQUESTS_DELTA_METRIC = "proc_net_snmp_ip_out_requests_delta"
PROC_NET_SNMP_IP_OUT_DISCARDS_DELTA_METRIC = "proc_net_snmp_ip_out_discards_delta"
PROC_NET_SNMP_IP_OUT_NO_ROUTES_DELTA_METRIC = "proc_net_snmp_ip_out_no_routes_delta"
PROC_NET_SNMP_IP_REASM_TIMEOUT_METRIC = "proc_net_snmp_ip_reasm_timeout"
PROC_NET_SNMP_IP_REASM_REQDS_DELTA_METRIC = "proc_net_snmp_ip_reasm_reqds_delta"
PROC_NET_SNMP_IP_REASM_OKS_DELTA_METRIC = "proc_net_snmp_ip_reasm_oks_delta"
PROC_NET_SNMP_IP_REASM_FAILS_DELTA_METRIC = "proc_net_snmp_ip_reasm_fails_delta"
PROC_NET_SNMP_IP_FRAG_OKS_DELTA_METRIC = "proc_net_snmp_ip_frag_oks_delta"
PROC_NET_SNMP_IP_FRAG_FAILS_DELTA_METRIC = "proc_net_snmp_ip_frag_fails_delta"
PROC_NET_SNMP_IP_FRAG_CREATES_DELTA_METRIC = "proc_net_snmp_ip_frag_creates_delta"
PROC_NET_SNMP_ICMP_IN_MSGS_DELTA_METRIC = "proc_net_snmp_icmp_in_msgs_delta"
PROC_NET_SNMP_ICMP_IN_ERRORS_DELTA_METRIC = "proc_net_snmp_icmp_in_errors_delta"
PROC_NET_SNMP_ICMP_IN_CSUM_ERRORS_DELTA_METRIC = (
    "proc_net_snmp_icmp_in_csum_errors_delta"
)
PROC_NET_SNMP_ICMP_IN_DEST_UNREACHS_DELTA_METRIC = (
    "proc_net_snmp_icmp_in_dest_unreachs_delta"
)
PROC_NET_SNMP_ICMP_IN_TIME_EXCDS_DELTA_METRIC = "proc_net_snmp_icmp_in_time_excds_delta"
PROC_NET_SNMP_ICMP_IN_PARM_PROBS_DELTA_METRIC = "proc_net_snmp_icmp_in_parm_probs_delta"
PROC_NET_SNMP_ICMP_IN_SRC_QUENCHS_DELTA_METRIC = (
    "proc_net_snmp_icmp_in_src_quenchs_delta"
)
PROC_NET_SNMP_ICMP_IN_REDIRECTS_DELTA_METRIC = "proc_net_snmp_icmp_in_redirects_delta"
PROC_NET_SNMP_ICMP_IN_ECHOS_DELTA_METRIC = "proc_net_snmp_icmp_in_echos_delta"
PROC_NET_SNMP_ICMP_IN_ECHO_REPS_DELTA_METRIC = "proc_net_snmp_icmp_in_echo_reps_delta"
PROC_NET_SNMP_ICMP_IN_TIMESTAMPS_DELTA_METRIC = "proc_net_snmp_icmp_in_timestamps_delta"
PROC_NET_SNMP_ICMP_IN_TIMESTAMP_REPS_DELTA_METRIC = (
    "proc_net_snmp_icmp_in_timestamp_reps_delta"
)
PROC_NET_SNMP_ICMP_IN_ADDR_MASKS_DELTA_METRIC = "proc_net_snmp_icmp_in_addr_masks_delta"
PROC_NET_SNMP_ICMP_IN_ADDR_MASK_REPS_DELTA_METRIC = (
    "proc_net_snmp_icmp_in_addr_mask_reps_delta"
)
PROC_NET_SNMP_ICMP_OUT_MSGS_DELTA_METRIC = "proc_net_snmp_icmp_out_msgs_delta"
PROC_NET_SNMP_ICMP_OUT_ERRORS_DELTA_METRIC = "proc_net_snmp_icmp_out_errors_delta"
PROC_NET_SNMP_ICMP_OUT_DEST_UNREACHS_DELTA_METRIC = (
    "proc_net_snmp_icmp_out_dest_unreachs_delta"
)
PROC_NET_SNMP_ICMP_OUT_TIME_EXCDS_DELTA_METRIC = (
    "proc_net_snmp_icmp_out_time_excds_delta"
)
PROC_NET_SNMP_ICMP_OUT_PARM_PROBS_DELTA_METRIC = (
    "proc_net_snmp_icmp_out_parm_probs_delta"
)
PROC_NET_SNMP_ICMP_OUT_SRC_QUENCHS_DELTA_METRIC = (
    "proc_net_snmp_icmp_out_src_quenchs_delta"
)
PROC_NET_SNMP_ICMP_OUT_REDIRECTS_DELTA_METRIC = "proc_net_snmp_icmp_out_redirects_delta"
PROC_NET_SNMP_ICMP_OUT_ECHOS_DELTA_METRIC = "proc_net_snmp_icmp_out_echos_delta"
PROC_NET_SNMP_ICMP_OUT_ECHO_REPS_DELTA_METRIC = "proc_net_snmp_icmp_out_echo_reps_delta"
PROC_NET_SNMP_ICMP_OUT_TIMESTAMPS_DELTA_METRIC = (
    "proc_net_snmp_icmp_out_timestamps_delta"
)
PROC_NET_SNMP_ICMP_OUT_TIMESTAMP_REPS_DELTA_METRIC = (
    "proc_net_snmp_icmp_out_timestamp_reps_delta"
)
PROC_NET_SNMP_ICMP_OUT_ADDR_MASKS_DELTA_METRIC = (
    "proc_net_snmp_icmp_out_addr_masks_delta"
)
PROC_NET_SNMP_ICMP_OUT_ADDR_MASK_REPS_DELTA_METRIC = (
    "proc_net_snmp_icmp_out_addr_mask_reps_delta"
)
PROC_NET_SNMP_ICMPMSG_IN_TYPE3_DELTA_METRIC = "proc_net_snmp_icmpmsg_in_type3_delta"
PROC_NET_SNMP_ICMPMSG_OUT_TYPE3_DELTA_METRIC = "proc_net_snmp_icmpmsg_out_type3_delta"
PROC_NET_SNMP_TCP_RTO_ALGORITHM_METRIC = "proc_net_snmp_tcp_rto_algorithm"
PROC_NET_SNMP_TCP_RTO_MIN_METRIC = "proc_net_snmp_tcp_rto_min"
PROC_NET_SNMP_TCP_RTO_MAX_METRIC = "proc_net_snmp_tcp_rto_max"
PROC_NET_SNMP_TCP_MAX_CONN_METRIC = "proc_net_snmp_tcp_max_conn"
PROC_NET_SNMP_TCP_ACTIVE_OPENS_DELTA_METRIC = "proc_net_snmp_tcp_active_opens_delta"
PROC_NET_SNMP_TCP_PASSIVE_OPENS_DELTA_METRIC = "proc_net_snmp_tcp_passive_opens_delta"
PROC_NET_SNMP_TCP_ATTEMPT_FAILS_DELTA_METRIC = "proc_net_snmp_tcp_attempt_fails_delta"
PROC_NET_SNMP_TCP_ESTAB_RESETS_DELTA_METRIC = "proc_net_snmp_tcp_estab_resets_delta"
PROC_NET_SNMP_TCP_CURR_ESTAB_METRIC = "proc_net_snmp_tcp_curr_estab"
PROC_NET_SNMP_TCP_IN_SEGS_DELTA_METRIC = "proc_net_snmp_tcp_in_segs_delta"
PROC_NET_SNMP_TCP_OUT_SEGS_DELTA_METRIC = "proc_net_snmp_tcp_out_segs_delta"
PROC_NET_SNMP_TCP_RETRANS_SEGS_DELTA_METRIC = "proc_net_snmp_tcp_retrans_segs_delta"
PROC_NET_SNMP_TCP_IN_ERRS_DELTA_METRIC = "proc_net_snmp_tcp_in_errs_delta"
PROC_NET_SNMP_TCP_OUT_RSTS_DELTA_METRIC = "proc_net_snmp_tcp_out_rsts_delta"
PROC_NET_SNMP_TCP_IN_CSUM_ERRORS_DELTA_METRIC = "proc_net_snmp_tcp_in_csum_errors_delta"
PROC_NET_SNMP_UDP_IN_DATAGRAMS_DELTA_METRIC = "proc_net_snmp_udp_in_datagrams_delta"
PROC_NET_SNMP_UDP_NO_PORTS_DELTA_METRIC = "proc_net_snmp_udp_no_ports_delta"
PROC_NET_SNMP_UDP_IN_ERRORS_DELTA_METRIC = "proc_net_snmp_udp_in_errors_delta"
PROC_NET_SNMP_UDP_OUT_DATAGRAMS_DELTA_METRIC = "proc_net_snmp_udp_out_datagrams_delta"
PROC_NET_SNMP_UDP_RCVBUF_ERRORS_DELTA_METRIC = "proc_net_snmp_udp_rcvbuf_errors_delta"
PROC_NET_SNMP_UDP_SNDBUF_ERRORS_DELTA_METRIC = "proc_net_snmp_udp_sndbuf_errors_delta"
PROC_NET_SNMP_UDP_IN_CSUM_ERRORS_DELTA_METRIC = "proc_net_snmp_udp_in_csum_errors_delta"
PROC_NET_SNMP_UDP_IGNORED_MULTI_DELTA_METRIC = "proc_net_snmp_udp_ignored_multi_delta"
PROC_NET_SNMP_UDP_MEM_ERRORS_DELTA_METRIC = "proc_net_snmp_udp_mem_errors_delta"
PROC_NET_SNMP_UDPLITE_IN_DATAGRAMS_DELTA_METRIC = (
    "proc_net_snmp_udplite_in_datagrams_delta"
)
PROC_NET_SNMP_UDPLITE_NO_PORTS_DELTA_METRIC = "proc_net_snmp_udplite_no_ports_delta"
PROC_NET_SNMP_UDPLITE_IN_ERRORS_DELTA_METRIC = "proc_net_snmp_udplite_in_errors_delta"
PROC_NET_SNMP_UDPLITE_OUT_DATAGRAMS_DELTA_METRIC = (
    "proc_net_snmp_udplite_out_datagrams_delta"
)
PROC_NET_SNMP_UDPLITE_RCVBUF_ERRORS_DELTA_METRIC = (
    "proc_net_snmp_udplite_rcvbuf_errors_delta"
)
PROC_NET_SNMP_UDPLITE_SNDBUF_ERRORS_DELTA_METRIC = (
    "proc_net_snmp_udplite_sndbuf_errors_delta"
)
PROC_NET_SNMP_UDPLITE_IN_CSUM_ERRORS_DELTA_METRIC = (
    "proc_net_snmp_udplite_in_csum_errors_delta"
)
PROC_NET_SNMP_UDPLITE_IGNORED_MULTI_DELTA_METRIC = (
    "proc_net_snmp_udplite_ignored_multi_delta"
)
PROC_NET_SNMP_UDPLITE_MEM_ERRORS_DELTA_METRIC = "proc_net_snmp_udplite_mem_errors_delta"

PROC_NET_SNMP_INTERVAL_METRIC_NAME = "proc_net_snmp_metrics_delta_sec"

proc_net_snmp_index_to_metric_name = {
    procfs.NET_SNMP_IP_FORWARDING: PROC_NET_SNMP_IP_FORWARDING_METRIC,
    procfs.NET_SNMP_IP_DEFAULT_TTL: PROC_NET_SNMP_IP_DEFAULT_TTL_METRIC,
    procfs.NET_SNMP_IP_IN_RECEIVES: PROC_NET_SNMP_IP_IN_RECEIVES_DELTA_METRIC,
    procfs.NET_SNMP_IP_IN_HDR_ERRORS: PROC_NET_SNMP_IP_IN_HDR_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_IP_IN_ADDR_ERRORS: PROC_NET_SNMP_IP_IN_ADDR_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_IP_FORW_DATAGRAMS: PROC_NET_SNMP_IP_FORW_DATAGRAMS_DELTA_METRIC,
    procfs.NET_SNMP_IP_IN_UNKNOWN_PROTOS: PROC_NET_SNMP_IP_IN_UNKNOWN_PROTOS_DELTA_METRIC,
    procfs.NET_SNMP_IP_IN_DISCARDS: PROC_NET_SNMP_IP_IN_DISCARDS_DELTA_METRIC,
    procfs.NET_SNMP_IP_IN_DELIVERS: PROC_NET_SNMP_IP_IN_DELIVERS_DELTA_METRIC,
    procfs.NET_SNMP_IP_OUT_REQUESTS: PROC_NET_SNMP_IP_OUT_REQUESTS_DELTA_METRIC,
    procfs.NET_SNMP_IP_OUT_DISCARDS: PROC_NET_SNMP_IP_OUT_DISCARDS_DELTA_METRIC,
    procfs.NET_SNMP_IP_OUT_NO_ROUTES: PROC_NET_SNMP_IP_OUT_NO_ROUTES_DELTA_METRIC,
    procfs.NET_SNMP_IP_REASM_TIMEOUT: PROC_NET_SNMP_IP_REASM_TIMEOUT_METRIC,
    procfs.NET_SNMP_IP_REASM_REQDS: PROC_NET_SNMP_IP_REASM_REQDS_DELTA_METRIC,
    procfs.NET_SNMP_IP_REASM_OKS: PROC_NET_SNMP_IP_REASM_OKS_DELTA_METRIC,
    procfs.NET_SNMP_IP_REASM_FAILS: PROC_NET_SNMP_IP_REASM_FAILS_DELTA_METRIC,
    procfs.NET_SNMP_IP_FRAG_OKS: PROC_NET_SNMP_IP_FRAG_OKS_DELTA_METRIC,
    procfs.NET_SNMP_IP_FRAG_FAILS: PROC_NET_SNMP_IP_FRAG_FAILS_DELTA_METRIC,
    procfs.NET_SNMP_IP_FRAG_CREATES: PROC_NET_SNMP_IP_FRAG_CREATES_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_MSGS: PROC_NET_SNMP_ICMP_IN_MSGS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_ERRORS: PROC_NET_SNMP_ICMP_IN_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_CSUM_ERRORS: PROC_NET_SNMP_ICMP_IN_CSUM_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_DEST_UNREACHS: PROC_NET_SNMP_ICMP_IN_DEST_UNREACHS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_TIME_EXCDS: PROC_NET_SNMP_ICMP_IN_TIME_EXCDS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_PARM_PROBS: PROC_NET_SNMP_ICMP_IN_PARM_PROBS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_SRC_QUENCHS: PROC_NET_SNMP_ICMP_IN_SRC_QUENCHS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_REDIRECTS: PROC_NET_SNMP_ICMP_IN_REDIRECTS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_ECHOS: PROC_NET_SNMP_ICMP_IN_ECHOS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_ECHO_REPS: PROC_NET_SNMP_ICMP_IN_ECHO_REPS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_TIMESTAMPS: PROC_NET_SNMP_ICMP_IN_TIMESTAMPS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_TIMESTAMP_REPS: PROC_NET_SNMP_ICMP_IN_TIMESTAMP_REPS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_ADDR_MASKS: PROC_NET_SNMP_ICMP_IN_ADDR_MASKS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_IN_ADDR_MASK_REPS: PROC_NET_SNMP_ICMP_IN_ADDR_MASK_REPS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_MSGS: PROC_NET_SNMP_ICMP_OUT_MSGS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_ERRORS: PROC_NET_SNMP_ICMP_OUT_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_DEST_UNREACHS: PROC_NET_SNMP_ICMP_OUT_DEST_UNREACHS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_TIME_EXCDS: PROC_NET_SNMP_ICMP_OUT_TIME_EXCDS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_PARM_PROBS: PROC_NET_SNMP_ICMP_OUT_PARM_PROBS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_SRC_QUENCHS: PROC_NET_SNMP_ICMP_OUT_SRC_QUENCHS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_REDIRECTS: PROC_NET_SNMP_ICMP_OUT_REDIRECTS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_ECHOS: PROC_NET_SNMP_ICMP_OUT_ECHOS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_ECHO_REPS: PROC_NET_SNMP_ICMP_OUT_ECHO_REPS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_TIMESTAMPS: PROC_NET_SNMP_ICMP_OUT_TIMESTAMPS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_TIMESTAMP_REPS: PROC_NET_SNMP_ICMP_OUT_TIMESTAMP_REPS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_ADDR_MASKS: PROC_NET_SNMP_ICMP_OUT_ADDR_MASKS_DELTA_METRIC,
    procfs.NET_SNMP_ICMP_OUT_ADDR_MASK_REPS: PROC_NET_SNMP_ICMP_OUT_ADDR_MASK_REPS_DELTA_METRIC,
    procfs.NET_SNMP_ICMPMSG_IN_TYPE3: PROC_NET_SNMP_ICMPMSG_IN_TYPE3_DELTA_METRIC,
    procfs.NET_SNMP_ICMPMSG_OUT_TYPE3: PROC_NET_SNMP_ICMPMSG_OUT_TYPE3_DELTA_METRIC,
    procfs.NET_SNMP_TCP_RTO_ALGORITHM: PROC_NET_SNMP_TCP_RTO_ALGORITHM_METRIC,
    procfs.NET_SNMP_TCP_RTO_MIN: PROC_NET_SNMP_TCP_RTO_MIN_METRIC,
    procfs.NET_SNMP_TCP_RTO_MAX: PROC_NET_SNMP_TCP_RTO_MAX_METRIC,
    procfs.NET_SNMP_TCP_MAX_CONN: PROC_NET_SNMP_TCP_MAX_CONN_METRIC,
    procfs.NET_SNMP_TCP_ACTIVE_OPENS: PROC_NET_SNMP_TCP_ACTIVE_OPENS_DELTA_METRIC,
    procfs.NET_SNMP_TCP_PASSIVE_OPENS: PROC_NET_SNMP_TCP_PASSIVE_OPENS_DELTA_METRIC,
    procfs.NET_SNMP_TCP_ATTEMPT_FAILS: PROC_NET_SNMP_TCP_ATTEMPT_FAILS_DELTA_METRIC,
    procfs.NET_SNMP_TCP_ESTAB_RESETS: PROC_NET_SNMP_TCP_ESTAB_RESETS_DELTA_METRIC,
    procfs.NET_SNMP_TCP_CURR_ESTAB: PROC_NET_SNMP_TCP_CURR_ESTAB_METRIC,
    procfs.NET_SNMP_TCP_IN_SEGS: PROC_NET_SNMP_TCP_IN_SEGS_DELTA_METRIC,
    procfs.NET_SNMP_TCP_OUT_SEGS: PROC_NET_SNMP_TCP_OUT_SEGS_DELTA_METRIC,
    procfs.NET_SNMP_TCP_RETRANS_SEGS: PROC_NET_SNMP_TCP_RETRANS_SEGS_DELTA_METRIC,
    procfs.NET_SNMP_TCP_IN_ERRS: PROC_NET_SNMP_TCP_IN_ERRS_DELTA_METRIC,
    procfs.NET_SNMP_TCP_OUT_RSTS: PROC_NET_SNMP_TCP_OUT_RSTS_DELTA_METRIC,
    procfs.NET_SNMP_TCP_IN_CSUM_ERRORS: PROC_NET_SNMP_TCP_IN_CSUM_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDP_IN_DATAGRAMS: PROC_NET_SNMP_UDP_IN_DATAGRAMS_DELTA_METRIC,
    procfs.NET_SNMP_UDP_NO_PORTS: PROC_NET_SNMP_UDP_NO_PORTS_DELTA_METRIC,
    procfs.NET_SNMP_UDP_IN_ERRORS: PROC_NET_SNMP_UDP_IN_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDP_OUT_DATAGRAMS: PROC_NET_SNMP_UDP_OUT_DATAGRAMS_DELTA_METRIC,
    procfs.NET_SNMP_UDP_RCVBUF_ERRORS: PROC_NET_SNMP_UDP_RCVBUF_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDP_SNDBUF_ERRORS: PROC_NET_SNMP_UDP_SNDBUF_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDP_IN_CSUM_ERRORS: PROC_NET_SNMP_UDP_IN_CSUM_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDP_IGNORED_MULTI: PROC_NET_SNMP_UDP_IGNORED_MULTI_DELTA_METRIC,
    procfs.NET_SNMP_UDP_MEM_ERRORS: PROC_NET_SNMP_UDP_MEM_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDPLITE_IN_DATAGRAMS: PROC_NET_SNMP_UDPLITE_IN_DATAGRAMS_DELTA_METRIC,
    procfs.NET_SNMP_UDPLITE_NO_PORTS: PROC_NET_SNMP_UDPLITE_NO_PORTS_DELTA_METRIC,
    procfs.NET_SNMP_UDPLITE_IN_ERRORS: PROC_NET_SNMP_UDPLITE_IN_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDPLITE_OUT_DATAGRAMS: PROC_NET_SNMP_UDPLITE_OUT_DATAGRAMS_DELTA_METRIC,
    procfs.NET_SNMP_UDPLITE_RCVBUF_ERRORS: PROC_NET_SNMP_UDPLITE_RCVBUF_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDPLITE_SNDBUF_ERRORS: PROC_NET_SNMP_UDPLITE_SNDBUF_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDPLITE_IN_CSUM_ERRORS: PROC_NET_SNMP_UDPLITE_IN_CSUM_ERRORS_DELTA_METRIC,
    procfs.NET_SNMP_UDPLITE_IGNORED_MULTI: PROC_NET_SNMP_UDPLITE_IGNORED_MULTI_DELTA_METRIC,
    procfs.NET_SNMP_UDPLITE_MEM_ERRORS: PROC_NET_SNMP_UDPLITE_MEM_ERRORS_DELTA_METRIC,
}

proc_net_snmp_non_delta_index = set(
    [
        procfs.NET_SNMP_IP_DEFAULT_TTL,
        procfs.NET_SNMP_IP_FORWARDING,
        procfs.NET_SNMP_IP_REASM_TIMEOUT,
        procfs.NET_SNMP_TCP_CURR_ESTAB,
        procfs.NET_SNMP_TCP_MAX_CONN,
        procfs.NET_SNMP_TCP_RTO_ALGORITHM,
        procfs.NET_SNMP_TCP_RTO_MAX,
        procfs.NET_SNMP_TCP_RTO_MIN,
    ]
)
