package testutils

// Index to name maps:
var PidStatByteSliceFieldsIndexName = []string{
	"PID_STAT_COMM",
	"PID_STAT_STATE",
	"PID_STAT_PPID",
	"PID_STAT_PGRP",
	"PID_STAT_SESSION",
	"PID_STAT_TTY_NR",
	"PID_STAT_TPGID",
	"PID_STAT_FLAGS",
	"PID_STAT_PRIORITY",
	"PID_STAT_NICE",
	"PID_STAT_NUM_THREADS",
	"PID_STAT_STARTTIME",
	"PID_STAT_VSIZE",
	"PID_STAT_RSS",
	"PID_STAT_RSSLIM",
	"PID_STAT_PROCESSOR",
	"PID_STAT_RT_PRIORITY",
	"PID_STAT_POLICY",
}

var PidStatNumericFieldsIndexName = []string{
	"PID_STAT_MINFLT",
	"PID_STAT_MAJFLT",
	"PID_STAT_UTIME",
	"PID_STAT_STIME",
}

var PidStatusByteSliceFieldsIndexToName = []string{
	"PID_STATUS_UID",
	"PID_STATUS_GID",
	"PID_STATUS_GROUPS",
	"PID_STATUS_VM_PEAK",
	"PID_STATUS_VM_SIZE",
	"PID_STATUS_VM_LCK",
	"PID_STATUS_VM_PIN",
	"PID_STATUS_VM_HWM",
	"PID_STATUS_VM_RSS",
	"PID_STATUS_RSS_ANON",
	"PID_STATUS_RSS_FILE",
	"PID_STATUS_RSS_SHMEM",
	"PID_STATUS_VM_DATA",
	"PID_STATUS_VM_STK",
	"PID_STATUS_VM_EXE",
	"PID_STATUS_VM_LIB",
	"PID_STATUS_VM_PTE",
	"PID_STATUS_VM_PMD",
	"PID_STATUS_VM_SWAP",
	"PID_STATUS_HUGETLBPAGES",
	"PID_STATUS_CPUS_ALLOWED_LIST",
	"PID_STATUS_MEMS_ALLOWED_LIST",
}

var PidStatusNumericFieldsIndexToName = []string{
	"PID_STATUS_VOLUNTARY_CTXT_SWITCHES",
	"PID_STATUS_NONVOLUNTARY_CTXT_SWITCHES",
}
