#!/bin/bash --noprofile

this_script=${0##*/}
case "$0" in
    /*|*/*) 
        this_dir=$(cd $(dirname $0) && pwd)
    ;;
    *) 
        this_dir=$(cd $(dirname $(which $0)) && pwd)
    ;;
esac

platform="$1"; shift
volumes_dir=volumes${platform:+/}$platform

set -e
cd $this_dir
lsvmi_dir=$(realpath "../../../../../linux-stats-victoriametrics-importer")
if [[ ! -d $volumes_dir/runtime ]]; then
    (set -x; mkdir -p $volumes_dir/runtime)
fi
if [[ "$(readlink $volumes_dir/linux-stats-victoriametrics-importer)" != "$lsvmi_dir" ]]; then
    (set -x; ln -fs "$lsvmi_dir" $volumes_dir/linux-stats-victoriametrics-importer)
fi
