{
 "title": "internal_metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   {
    "name": "task_id",
    "label": "TaskID",
    "query": {
     "query": "lsvmi_task_scheduled_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "compressor",
    "label": "CompressorID",
    "query": {
     "query": "lsvmi_compressor_compression_factor{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "url",
    "label": "EP url",
    "query": {
     "query": "lsvmi_http_ep_state{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "generator_id",
    "label": "GeneratorID",
    "query": {
     "query": "lsvmi_metrics_gen_invocation_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   { "name": "interval", "query": "5s" }
  ]
 },
 "panels": [
  {
   "title": "Agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agents",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "lsvmi_uptime_sec\n* on (instance, hostname) group_right(version, gitinfo)\nos_info",
       "legendFormat": "__auto"
      },
      {
       "expr": "os_uptime_sec\n* on (instance, hostname) group_right()\nos_info",
       "legendFormat": "__auto"
      },
      {
       "expr": "os_btime_sec * 1000\n* on (instance, hostname) group_right()\nos_info",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Internal Metrics Actual Scan Interval",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "lsvmi_internal_metrics_delta_sec{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Up Agents Timeline",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(lsvmi_uptime_sec{instance=~\"${instance}\",hostname=~\"${hostname}\"}) by (instance, hostname)",
       "legendFormat": "{{hostname}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Scheduled# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_task_scheduled_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",task_id=~\"${task_id}\"}",
       "legendFormat": "{{task_id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Task Executed# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_task_executed_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",task_id=~\"${task_id}\"}",
       "legendFormat": "{{task_id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Task Average Runtime",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "lsvmi_task_interval_avg_runtime_sec{instance=~\"${instance}\",hostname=~\"${hostname}\",task_id=~\"${task_id}\"}",
       "legendFormat": "{{task_id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Task Delayed# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_task_delayed_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",task_id=~\"${task_id}\"}",
       "legendFormat": "{{task_id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Task Overrun# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_task_overrun_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",task_id=~\"${task_id}\"}",
       "legendFormat": "{{task_id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Task Deadline Hack# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_task_deadline_hack_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",task_id=~\"${task_id}\"}",
       "legendFormat": "{{task_id}}({{hostname}}/{{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Compressors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "lsvmi_compressor_read_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Read Bytes Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "lsvmi_compressor_read_byte_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Compression Factor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
     "targets": [
      {
       "expr": "lsvmi_compressor_compression_factor{instance=~\"${instance}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Send# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "lsvmi_compressor_send_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Send Byte Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "lsvmi_compressor_send_byte_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Timeout Flush# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_compressor_tout_flush_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Error# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
     "targets": [
      {
       "expr": "lsvmi_compressor_send_error_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "send_err(c{{compressor}}/{{hostname}}/{{instance}})"
      },
      {
       "expr": "lsvmi_compressor_write_error_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "write_err(c{{compressor}}/{{hostname}}/{{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Endpoint State",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_http_ep_state{instance=~\"${instance}\",hostname=~\"${hostname}\",url=~\"${url}\"}",
       "legendFormat": "instance={{instance}},hostname={{hostname}},url={{url}}"
      }
     ]
    },
    {
     "title": "HTTP Endpoint Send Buffer# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_http_ep_send_buffer_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",url=~\"${url}\"}",
       "legendFormat": "{{hostname}}/{{instance}}->{{url}}"
      }
     ]
    },
    {
     "title": "HTTP Endpoint Send Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "lsvmi_http_ep_send_buffer_byte_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",url=~\"${url}\"} * 8 / on (instance, hostname) group_left lsvmi_internal_metrics_delta_sec{instance=~\"${instance}\",hostname=~\"${hostname}\"} ",
       "legendFormat": "{{hostname}}/{{instance}}->{{url}}"
      }
     ]
    },
    {
     "title": "HTTP Endpoint State",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_http_ep_state{instance=~\"${instance}\",hostname=~\"${hostname}\",url=~\"${url}\"}",
       "legendFormat": "{{hostname}}/{{instance}}->{{url}}"
      }
     ]
    },
    {
     "title": "HTTP Endpoint Error# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_http_ep_send_buffer_error_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",url=~\"${url}\"}",
       "legendFormat": "send_err({{hostname}}/{{instance}}->{{url}})"
      },
      {
       "expr": "lsvmi_http_ep_healthcheck_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",url=~\"${url}\"}",
       "legendFormat": "healthchk({{hostname}}/{{instance}}->{{url}})"
      },
      {
       "expr": "lsvmi_http_ep_healthcheck_error_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",url=~\"${url}\"}",
       "legendFormat": "healthchk_err({{hostname}}/{{instance}}->{{url}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Generators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Generator Invocation# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "lsvmi_metrics_gen_invocation_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",id=~\"${generator_id}\"}",
       "legendFormat": "{{id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Actual Metrics# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "targets": [
      {
       "expr": "lsvmi_metrics_gen_actual_metrics_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",id=~\"${generator_id}\"}",
       "legendFormat": "{{id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Actual Metrics%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "lsvmi_metrics_gen_actual_metrics_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",id=~\"${generator_id}\"}\n/\nlsvmi_metrics_gen_total_metrics_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",id=~\"${generator_id}\"}",
       "legendFormat": "{{id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Metrics/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "lsvmi_metrics_gen_actual_metrics_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",id=~\"${generator_id}\"}\n/ on(instance,hostname) group_left\nlsvmi_internal_metrics_delta_sec{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Bytes# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "lsvmi_metrics_gen_bytes_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",id=~\"${generator_id}\"}",
       "legendFormat": "{{id}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Bytes/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lsvmi_metrics_gen_bytes_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",id=~\"${generator_id}\"}\n/ on(instance,hostname) group_left\nlsvmi_internal_metrics_delta_sec{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{id}}({{hostname}}/{{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "lsvmi_go_mem_sys_bytes{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "sys({{hostname}}/{{instance}})"
      },
      {
       "expr": "lsvmi_go_mem_heap_bytes{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "heap({{hostname}}/{{instance}})"
      },
      {
       "expr": "lsvmi_go_mem_heap_sys_bytes{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "heap_sys({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Malloc/Free# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "targets": [
      {
       "expr": "lsvmi_go_mem_malloc_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "malloc({{hostname}}/{{instance}})"
      },
      {
       "expr": "lsvmi_go_mem_free_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "free({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "In Use Object Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 16, "y": 6 },
     "targets": [
      {
       "expr": "lsvmi_go_mem_in_use_object_count{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Goroutine Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_go_num_goroutine{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "GC# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_go_mem_gc_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "lsvmi_proc_vsize{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "vzise({{hostname}}/{{instance}})"
      },
      {
       "expr": "lsvmi_proc_rss{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "rss({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lsvmi_proc_pcpu{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Thread#",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lsvmi_proc_num_threads{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}