#! /usr/bin/env python3

from dataclasses import dataclass, field
from typing import List

# JSON serialize-able NetSnmp6, matching profcs/net_snmp6_parser.go:

NET_SNMP6_IP6_IN_RECEIVES = 0
NET_SNMP6_IP6_IN_HDR_ERRORS = 1
NET_SNMP6_IP6_IN_TOO_BIG_ERRORS = 2
NET_SNMP6_IP6_IN_NO_ROUTES = 3
NET_SNMP6_IP6_IN_ADDR_ERRORS = 4
NET_SNMP6_IP6_IN_UNKNOWN_PROTOS = 5
NET_SNMP6_IP6_IN_TRUNCATED_PKTS = 6
NET_SNMP6_IP6_IN_DISCARDS = 7
NET_SNMP6_IP6_IN_DELIVERS = 8
NET_SNMP6_IP6_OUT_FORW_DATAGRAMS = 9
NET_SNMP6_IP6_OUT_REQUESTS = 10
NET_SNMP6_IP6_OUT_DISCARDS = 11
NET_SNMP6_IP6_OUT_NO_ROUTES = 12
NET_SNMP6_IP6_REASM_TIMEOUT = 13
NET_SNMP6_IP6_REASM_REQDS = 14
NET_SNMP6_IP6_REASM_OKS = 15
NET_SNMP6_IP6_REASM_FAILS = 16
NET_SNMP6_IP6_FRAG_OKS = 17
NET_SNMP6_IP6_FRAG_FAILS = 18
NET_SNMP6_IP6_FRAG_CREATES = 19
NET_SNMP6_IP6_IN_MCAST_PKTS = 20
NET_SNMP6_IP6_OUT_MCAST_PKTS = 21
NET_SNMP6_IP6_IN_OCTETS = 22
NET_SNMP6_IP6_OUT_OCTETS = 23
NET_SNMP6_IP6_IN_MCAST_OCTETS = 24
NET_SNMP6_IP6_OUT_MCAST_OCTETS = 25
NET_SNMP6_IP6_IN_BCAST_OCTETS = 26
NET_SNMP6_IP6_OUT_BCAST_OCTETS = 27
NET_SNMP6_IP6_IN_NO_ECT_PKTS = 28
NET_SNMP6_IP6_IN_ECT1_PKTS = 29
NET_SNMP6_IP6_IN_ECT0_PKTS = 30
NET_SNMP6_IP6_IN_CE_PKTS = 31
NET_SNMP6_ICMP6_IN_MSGS = 32
NET_SNMP6_ICMP6_IN_ERRORS = 33
NET_SNMP6_ICMP6_OUT_MSGS = 34
NET_SNMP6_ICMP6_OUT_ERRORS = 35
NET_SNMP6_ICMP6_IN_CSUM_ERRORS = 36
NET_SNMP6_ICMP6_IN_DEST_UNREACHS = 37
NET_SNMP6_ICMP6_IN_PKT_TOO_BIGS = 38
NET_SNMP6_ICMP6_IN_TIME_EXCDS = 39
NET_SNMP6_ICMP6_IN_PARM_PROBLEMS = 40
NET_SNMP6_ICMP6_IN_ECHOS = 41
NET_SNMP6_ICMP6_IN_ECHO_REPLIES = 42
NET_SNMP6_ICMP6_IN_GROUP_MEMB_QUERIES = 43
NET_SNMP6_ICMP6_IN_GROUP_MEMB_RESPONSES = 44
NET_SNMP6_ICMP6_IN_GROUP_MEMB_REDUCTIONS = 45
NET_SNMP6_ICMP6_IN_ROUTER_SOLICITS = 46
NET_SNMP6_ICMP6_IN_ROUTER_ADVERTISEMENTS = 47
NET_SNMP6_ICMP6_IN_NEIGHBOR_SOLICITS = 48
NET_SNMP6_ICMP6_IN_NEIGHBOR_ADVERTISEMENTS = 49
NET_SNMP6_ICMP6_IN_REDIRECTS = 50
NET_SNMP6_ICMP6_IN_MLD_V2_REPORTS = 51
NET_SNMP6_ICMP6_OUT_DEST_UNREACHS = 52
NET_SNMP6_ICMP6_OUT_PKT_TOO_BIGS = 53
NET_SNMP6_ICMP6_OUT_TIME_EXCDS = 54
NET_SNMP6_ICMP6_OUT_PARM_PROBLEMS = 55
NET_SNMP6_ICMP6_OUT_ECHOS = 56
NET_SNMP6_ICMP6_OUT_ECHO_REPLIES = 57
NET_SNMP6_ICMP6_OUT_GROUP_MEMB_QUERIES = 58
NET_SNMP6_ICMP6_OUT_GROUP_MEMB_RESPONSES = 59
NET_SNMP6_ICMP6_OUT_GROUP_MEMB_REDUCTIONS = 60
NET_SNMP6_ICMP6_OUT_ROUTER_SOLICITS = 61
NET_SNMP6_ICMP6_OUT_ROUTER_ADVERTISEMENTS = 62
NET_SNMP6_ICMP6_OUT_NEIGHBOR_SOLICITS = 63
NET_SNMP6_ICMP6_OUT_NEIGHBOR_ADVERTISEMENTS = 64
NET_SNMP6_ICMP6_OUT_REDIRECTS = 65
NET_SNMP6_ICMP6_OUT_MLD_V2_REPORTS = 66
NET_SNMP6_ICMP6_OUT_TYPE133 = 67
NET_SNMP6_ICMP6_OUT_TYPE135 = 68
NET_SNMP6_ICMP6_OUT_TYPE143 = 69
NET_SNMP6_UDP6_IN_DATAGRAMS = 70
NET_SNMP6_UDP6_NO_PORTS = 71
NET_SNMP6_UDP6_IN_ERRORS = 72
NET_SNMP6_UDP6_OUT_DATAGRAMS = 73
NET_SNMP6_UDP6_RCVBUF_ERRORS = 74
NET_SNMP6_UDP6_SNDBUF_ERRORS = 75
NET_SNMP6_UDP6_IN_CSUM_ERRORS = 76
NET_SNMP6_UDP6_IGNORED_MULTI = 77
NET_SNMP6_UDP6_MEM_ERRORS = 78
NET_SNMP6_UDPLITE6_IN_DATAGRAMS = 79
NET_SNMP6_UDPLITE6_NO_PORTS = 80
NET_SNMP6_UDPLITE6_IN_ERRORS = 81
NET_SNMP6_UDPLITE6_OUT_DATAGRAMS = 82
NET_SNMP6_UDPLITE6_RCVBUF_ERRORS = 83
NET_SNMP6_UDPLITE6_SNDBUF_ERRORS = 84
NET_SNMP6_UDPLITE6_IN_CSUM_ERRORS = 85
NET_SNMP6_UDPLITE6_MEM_ERRORS = 86

NET_SNMP6_NUM_VALUES = 87

netSnmp6IsUint32 = {
    NET_SNMP6_ICMP6_IN_MSGS,
    NET_SNMP6_ICMP6_IN_ERRORS,
    NET_SNMP6_ICMP6_OUT_MSGS,
    NET_SNMP6_ICMP6_OUT_ERRORS,
    NET_SNMP6_ICMP6_IN_CSUM_ERRORS,
    NET_SNMP6_ICMP6_IN_DEST_UNREACHS,
    NET_SNMP6_ICMP6_IN_PKT_TOO_BIGS,
    NET_SNMP6_ICMP6_IN_TIME_EXCDS,
    NET_SNMP6_ICMP6_IN_PARM_PROBLEMS,
    NET_SNMP6_ICMP6_IN_ECHOS,
    NET_SNMP6_ICMP6_IN_ECHO_REPLIES,
    NET_SNMP6_ICMP6_IN_GROUP_MEMB_QUERIES,
    NET_SNMP6_ICMP6_IN_GROUP_MEMB_RESPONSES,
    NET_SNMP6_ICMP6_IN_GROUP_MEMB_REDUCTIONS,
    NET_SNMP6_ICMP6_IN_ROUTER_SOLICITS,
    NET_SNMP6_ICMP6_IN_ROUTER_ADVERTISEMENTS,
    NET_SNMP6_ICMP6_IN_NEIGHBOR_SOLICITS,
    NET_SNMP6_ICMP6_IN_NEIGHBOR_ADVERTISEMENTS,
    NET_SNMP6_ICMP6_IN_REDIRECTS,
    NET_SNMP6_ICMP6_IN_MLD_V2_REPORTS,
    NET_SNMP6_ICMP6_OUT_DEST_UNREACHS,
    NET_SNMP6_ICMP6_OUT_PKT_TOO_BIGS,
    NET_SNMP6_ICMP6_OUT_TIME_EXCDS,
    NET_SNMP6_ICMP6_OUT_PARM_PROBLEMS,
    NET_SNMP6_ICMP6_OUT_ECHOS,
    NET_SNMP6_ICMP6_OUT_ECHO_REPLIES,
    NET_SNMP6_ICMP6_OUT_GROUP_MEMB_QUERIES,
    NET_SNMP6_ICMP6_OUT_GROUP_MEMB_RESPONSES,
    NET_SNMP6_ICMP6_OUT_GROUP_MEMB_REDUCTIONS,
    NET_SNMP6_ICMP6_OUT_ROUTER_SOLICITS,
    NET_SNMP6_ICMP6_OUT_ROUTER_ADVERTISEMENTS,
    NET_SNMP6_ICMP6_OUT_NEIGHBOR_SOLICITS,
    NET_SNMP6_ICMP6_OUT_NEIGHBOR_ADVERTISEMENTS,
    NET_SNMP6_ICMP6_OUT_REDIRECTS,
    NET_SNMP6_ICMP6_OUT_MLD_V2_REPORTS,
    NET_SNMP6_ICMP6_OUT_TYPE133,
    NET_SNMP6_ICMP6_OUT_TYPE135,
    NET_SNMP6_ICMP6_OUT_TYPE143,
    NET_SNMP6_UDP6_IN_DATAGRAMS,
    NET_SNMP6_UDP6_NO_PORTS,
    NET_SNMP6_UDP6_IN_ERRORS,
    NET_SNMP6_UDP6_OUT_DATAGRAMS,
    NET_SNMP6_UDP6_RCVBUF_ERRORS,
    NET_SNMP6_UDP6_SNDBUF_ERRORS,
    NET_SNMP6_UDP6_IN_CSUM_ERRORS,
    NET_SNMP6_UDP6_IGNORED_MULTI,
    NET_SNMP6_UDP6_MEM_ERRORS,
    NET_SNMP6_UDPLITE6_IN_DATAGRAMS,
    NET_SNMP6_UDPLITE6_NO_PORTS,
    NET_SNMP6_UDPLITE6_IN_ERRORS,
    NET_SNMP6_UDPLITE6_OUT_DATAGRAMS,
    NET_SNMP6_UDPLITE6_RCVBUF_ERRORS,
    NET_SNMP6_UDPLITE6_SNDBUF_ERRORS,
    NET_SNMP6_UDPLITE6_IN_CSUM_ERRORS,
    NET_SNMP6_UDPLITE6_MEM_ERRORS,
}


@dataclass
class NetSnmp6:
    Values: List[int] = field(default_factory=lambda: [0] * NET_SNMP6_NUM_VALUES)
    IsUint32: List[bool] = field(
        default_factory=lambda: [
            i in netSnmp6IsUint32 for i in range(NET_SNMP6_NUM_VALUES)
        ]
    )
