#! /usr/bin/env python3

# Must match procfs/pid_status_parser.go:
PID_STATUS_UID = 0
PID_STATUS_GID = 1
PID_STATUS_GROUPS = 2
PID_STATUS_VM_PEAK = 3
PID_STATUS_VM_SIZE = 4
PID_STATUS_VM_LCK = 5
PID_STATUS_VM_PIN = 6
PID_STATUS_VM_HWM = 7
PID_STATUS_VM_RSS = 8
PID_STATUS_RSS_ANON = 9
PID_STATUS_RSS_FILE = 10
PID_STATUS_RSS_SHMEM = 11
PID_STATUS_VM_DATA = 12
PID_STATUS_VM_STK = 13
PID_STATUS_VM_EXE = 14
PID_STATUS_VM_LIB = 15
PID_STATUS_VM_PTE = 16
PID_STATUS_VM_PMD = 17
PID_STATUS_VM_SWAP = 18
PID_STATUS_HUGETLBPAGES = 19
PID_STATUS_CPUS_ALLOWED_LIST = 20
PID_STATUS_MEMS_ALLOWED_LIST = 21
PID_STATUS_BYTE_SLICE_NUM_FIELDS = 22

PID_STATUS_VOLUNTARY_CTXT_SWITCHES = 0
PID_STATUS_NONVOLUNTARY_CTXT_SWITCHES = 1
PID_STATUS_ULONG_NUM_FIELDS = 2
