{
 "title": "proc_diskstats_metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   {
    "name": "maj_min",
    "label": "Maj:Min",
    "query": {
     "query": "proc_diskstats_info{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "disk_name",
    "label": "DiskName",
    "query": {
     "query": "proc_diskstats_info{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "mount_point",
    "label": "MountPoint",
    "query": {
     "query": "proc_mountinfo{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   { "name": "interval", "query": "5s" },
   { "name": "lookback", "query": "65s" },
   { "name": "threshold", "label": "Threshold", "query": "0" }
  ]
 },
 "panels": [
  {
   "title": "Disk Info (All)",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(\n  proc_diskstats_info{\n    instance=~\"${instance}\",\n    hostname=~\"${hostname}\",\n  }[${lookback}]\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Info (Mounted)",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "(\n  last_over_time(\n    proc_diskstats_info{\n      instance=~\"${instance}\",\n      hostname=~\"${hostname}\",\n    }[${lookback}]\n  ) > 0\n)\n* on (instance, hostname, maj_min) group_left(mount_point, fs_type, mount_source)\n(\n  last_over_time(\n    proc_mountinfo{\n      instance=~\"${instance}\",\n      hostname=~\"${hostname}\",\n    }[${lookback}]\n  ) > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reads Completed Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "proc_diskstats_num_reads_completed_delta{\n  instance=~\"${instance}\",hostname=~\"${hostname}\",maj_min=~\"${maj_min}\",name=~\"${disk_name}\"\n} >= ${threshold}",
     "legendFormat": "{{name}} ({{maj_min}})/{{hostname}}/{{instance}}"
    }
   ]
  }
 ]
}