{
 "title": "proc_stat_metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   { "name": "avg_interval", "label": "Avg Interval", "query": "1s,2s,5s,10s,20s,1m" },
   { "name": "interval", "query": "200ms" }
  ]
 },
 "panels": [
  {
   "title": "Per CPU + Avg %CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "guest %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"guest\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "guest_nice %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"guest_nice\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "idle %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"idle\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "iowait %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"iowait\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "irq %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"irq\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "nice %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"nice\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "softirq %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"softirq\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "steal %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"steal\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "system %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"system\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "user %CPU (per cpu + avg)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"user\",cpu=~\"${cpu}\",cpu!=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "all %CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "guest %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"guest\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "guest_nice %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"guest_nice\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "idle %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"idle\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "iowait %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"iowait\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "irq %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"irq\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "nice %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"nice\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "softirq %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"softirq\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "steal %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"steal\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "system %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"system\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "user %CPU (all)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",type=\"user\",cpu=\"all\"}",
       "legendFormat": "cpu{{cpu}}({{hostname}}/{{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "%CPU Explorer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stacked %CPU for cpu ${cpu}, ${hostname}/${instance}",
     "type": "timeseries",
     "description": "IMPORTANT! Must select a **specific** Instance, Hostname and CPU, \"All\" will NOT work.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_stat_cpu_pct{instance=\"${instance}\",hostname=\"${hostname}\",cpu=\"${cpu}\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Stacked %CPU for cpu ${cpu}, ${hostname}/${instance}, Avg / ${avg_interval}",
     "type": "timeseries",
     "description": "IMPORTANT! Must select a **specific** Instance, Hostname and CPU, \"All\" will NOT work.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg_over_time(\n        last_over_time(\n                proc_stat_cpu_pct{instance=\"${instance}\",hostname=\"${hostname}\",cpu=\"${cpu}\"}[5s200ms])[${avg_interval}]\n)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Boot/Up Time",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "expr": "proc_stat_btime_sec", "legendFormat": "__auto" },
      { "expr": "proc_stat_uptime_sec", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Swap In/Out Delta",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "proc_stat_swap_in_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{hostname}}/{{instance}})"
      },
      {
       "expr": "proc_stat_swap_out_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Page In/Out Delta",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "proc_stat_page_in_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{hostname}}/{{instance}})"
      },
      {
       "expr": "proc_stat_page_out_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Context Switches Delta",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "proc_stat_ctxt_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Fork# Delta",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "proc_stat_processes_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "process#({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Process Running/Blocked Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "targets": [
      {
       "expr": "proc_stat_procs_running_count{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "running({{hostname}}/{{instance}})"
      },
      {
       "expr": "proc_stat_procs_blocked_count{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "blocked({{hostname}}/{{instance}})"
      }
     ]
    },
    {
     "title": "Metric Interval",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "proc_stat_metrics_delta_sec{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "process#({{hostname}}/{{instance}})"
      }
     ]
    }
   ]
  }
 ]
}