{
 "title": "proc_net_snmp6_metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s" },
   { "name": "lookback", "query": "16s" },
   { "name": "data_threshold", "label": "Data Threshold", "query": "0" },
   { "name": "err_threshold", "label": "Error Threshold", "query": "0" }
  ]
 },
 "panels": [
  {
   "title": "IP6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ip6In Rates",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_ip6_in_kbps{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_mcast_kbps{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_bcast_kbps{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Ip6In Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_ip6_in_receives_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_hdr_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_too_big_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_no_routes_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_addr_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_unknown_protos_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_truncated_pkts_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_discards_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_delivers_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_mcast_pkts_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_no_ect_pkts_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_ect1_pkts_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_ect0_pkts_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_in_ce_pkts_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Ip6Out Rates",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_ip6_out_kbps{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_out_mcast_kbps{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_out_bcast_kbps{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Ip6Out Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_ip6_out_forw_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_out_requests_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_out_discards_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_out_no_routes_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Ip6 Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_ip6_reasm_timeout_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_reasm_reqds_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_reasm_oks_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_reasm_fails_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_frag_oks_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_frag_fails_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_ip6_frag_creates_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "ICMP6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Icmp6In Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_icmp6_in_msgs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_csum_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_dest_unreachs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_pkt_too_bigs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_time_excds_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_parm_problems_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_echos_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_echo_replies_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_group_memb_queries_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_group_memb_responses_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_group_memb_reductions_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_router_solicits_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_router_advertisements_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_neighbor_advertisements_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_redirects_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_in_mld_v2_reports_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Icmp6Out Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_icmp6_out_msgs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_dest_unreachs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_pkt_too_bigs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_time_excds_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_parm_problems_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_echos_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_echo_replies_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_group_memb_queries_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_group_memb_responses_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_group_memb_reductions_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_router_solicits_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_router_advertisements_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_neighbor_solicits_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_neighbor_advertisements_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_redirects_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_mld_v2_reports_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_type133_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_type135_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_icmp6_out_type143_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "UDP6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Udp6In Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_udp6_in_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udp6_in_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udp6_rcvbuf_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udp6_in_csum_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udp6_ignored_multi_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Udp6Out Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_udp6_out_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udp6_sndbuf_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Udp6 Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_udp6_no_ports_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udp6_mem_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "UDPLite",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Udplite6In Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_udplite6_in_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udplite6_in_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udplite6_rcvbuf_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udplite6_in_csum_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Udplite6Out Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_udplite6_out_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udplite6_sndbuf_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Udplite6 Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp6_udplite6_no_ports_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp6_udplite6_mem_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    }
   ]
  }
 ]
}