{
 "title": "proc_pid_metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   {
    "name": "cmd",
    "label": "Cmd",
    "query": {
     "query": "proc_pid_cmdline{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "args",
    "label": "Args",
    "query": {
     "query": "proc_pid_cmdline{instance=~\"${instance}\",hostname=~\"${hostname}\",cmd=~\"${cmd}\"}"
    }
   },
   {
    "name": "threads",
    "label": "Threads",
    "query": "On : \".*\", Off : \"\", Only : \".+\""
   },
   {
    "name": "part",
    "label": "Partition",
    "query": {
     "query": "proc_pid_metrics_delta_sec{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   { "name": "interval", "query": "1s" },
   { "name": "full_cycle", "query": "15" },
   { "name": "max_interval", "query": "5" }
  ]
 },
 "panels": [
  {
   "title": "/proc/PID/stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top View %CPU: %last, %max over ${max_interval}s, %avg over ${full_cycle}s",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "(proc_pid_stat_state{instance=~\"${instance}\", hostname=~\"${hostname}\", tid=~${threads}} > 0)\n* on (instance, hostname, pid) group_left(cmd, args)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_pcpu{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\nand on (instance, hostname, pid)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_cpu_num{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (instance, hostname, pid) group_left()\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "proc_pid_stat_rss_bytes{instance=~\"${instance}\",hostname=~\"${hostname}\"}\n* on (instance, hostname, pid)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max_over_time(proc_pid_stat_pcpu{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}[${max_interval}s])\nand on (instance, hostname, pid)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum_over_time(proc_pid_stat_pcpu{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}[${full_cycle}s])/${full_cycle})\nand on (instance, hostname, pid)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "%CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_pid_stat_pcpu{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "%CPU (System)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_pid_stat_stime_pcpu{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "%CPU (User)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "proc_pid_stat_utime_pcpu{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "RSS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_stat_rss_bytes{instance=~\"${instance}\",hostname=~\"${hostname}\"}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "RSSLIM",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_stat_rsslim_bytes{instance=~\"${instance}\",hostname=~\"${hostname}\"}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "VSIZE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_stat_vsize_bytes{instance=~\"${instance}\",hostname=~\"${hostname}\"}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "MinFlt Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_pid_stat_minflt_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (pid) group_left(cmd)\nproc_pid_cmdline{instance=~\"${instance}\",cmd=~\"${cmd}\"}",
       "legendFormat": "minflt_delta(cmd={{cmd}},pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "MajFlt Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_pid_stat_majflt_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "majflt_delta(cmd={{cmd}},pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Min/MajFlt Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_pid_stat_minflt_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "minflt_delta(cmd={{cmd}},pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      },
      {
       "expr": "proc_pid_stat_majflt_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (pid) group_left(cmd)\nproc_pid_cmdline{instance=~\"${instance}\",cmd=~\"${cmd}\"}",
       "legendFormat": "majflt_delta(cmd={{cmd}},pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "/proc/PID/status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Status Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "proc_pid_status_info{instance=~\"${instance}\",hostname=~\"${hostname}\"}\n* on (instance, hostname, pid) group_left(cmd, args)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VM Data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_status_vm_data{instance=~\"${instance}\",hostname=~\"${hostname}\"}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "VM Exe",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_status_vm_exe{instance=~\"${instance}\",hostname=~\"${hostname}\"}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "VM Swap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_status_vm_swap{instance=~\"${instance}\",hostname=~\"${hostname}\"}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "VM Stk",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_status_vm_stk{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "RSS Anon",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_status_rss_anon{instance=~\"${instance}\",hostname=~\"${hostname}\"}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "RSS File",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_status_rss_file{instance=~\"${instance}\",hostname=~\"${hostname}\"}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "RSS ShMem",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "last_over_time(proc_pid_status_rss_shmem{instance=~\"${instance}\",hostname=~\"${hostname}\"}[${full_cycle}])\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "{{cmd}}(pid={{pid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Voluntary Ctx Switch Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_pid_status_vol_ctx_switch_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "vol_ctx_delta(cmd={{cmd}},pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Non Voluntary Ctx Switch Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_pid_status_nonvol_ctx_switch_delta{instance=~\"${instance}\",hostname=~\"${hostname}\",tid=~${threads}}\n* on (pid) group_left(cmd)\n(last_over_time(proc_pid_cmdline{instance=~\"${instance}\", hostname=~\"${hostname}\", cmd=~\"${cmd}\"}[${full_cycle}]) > 0)",
       "legendFormat": "vol_ctx_delta(cmd={{cmd}},pid={{pid}},tid={{tid}},node={{hostname}},inst={{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "PID Counts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{__name__=~\"proc_pid_.*_count\",instance=~\"${instance}\",hostname=~\"${hostname}\",part=~\"${part}\"}",
       "legendFormat": "{{__name__}}(part={{part}},host={{hostname}},inst={{instance}})"
      }
     ]
    }
   ]
  }
 ]
}