{
 "title": "statfs_metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   {
    "name": "fs",
    "label": "Filesystem",
    "query": {
     "query": "statfs_enabled{instance=~\"${instance}\",hostname=~\"${hostname}\"}"
    }
   },
   { "name": "interval", "query": "5s" },
   { "name": "lookback", "query": "65s" }
  ]
 },
 "panels": [
  {
   "title": "Filesystems At A Glance",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_bsize{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_blocks{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_bfree{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_bavail{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_files{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_ffree{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_total_size_kb{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"}) / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_free_size_kb{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"}) / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_avail_size_kb{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"}) / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_free_pct{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, hostname, fs, fs_type, mount_point) (statfs_enabled{instance=~\"${instance}\",hostname=~\"${hostname}\",fs=~\"${fs}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stats For ${hostname} (specific host required!)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Stats For ${fs} on ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "statfs_blocks{instance=~\"${instance}\",hostname=\"${hostname}\",fs=~\"${fs}\"}",
       "legendFormat": "total(fs={{fs}},mnt={{mount_point}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "statfs_bfree{instance=~\"${instance}\",hostname=\"${hostname}\",fs=~\"${fs}\"}",
       "legendFormat": "free(fs={{fs}},mnt={{mount_point}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "statfs_bavail{instance=~\"${instance}\",hostname=\"${hostname}\",fs=~\"${fs}\"}",
       "legendFormat": "avail(fs={{fs}},mnt={{mount_point}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Size Stats For ${fs} on ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "statfs_total_size_kb{instance=~\"${instance}\",hostname=\"${hostname}\",fs=~\"${fs}\"}",
       "legendFormat": "total(fs={{fs}},mnt={{mount_point}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "statfs_free_size_kb{instance=~\"${instance}\",hostname=\"${hostname}\",fs=~\"${fs}\"}",
       "legendFormat": "free(fs={{fs}},mnt={{mount_point}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "statfs_avail_size_kb{instance=~\"${instance}\",hostname=\"${hostname}\",fs=~\"${fs}\"}",
       "legendFormat": "avail(fs={{fs}},mnt={{mount_point}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "statfs_free_pct{instance=~\"${instance}\",hostname=\"${hostname}\",fs=~\"${fs}\"}",
       "legendFormat": "%free(fs={{fs}},mnt={{mount_point}},host={{hostname}},inst={{instance}})"
      }
     ]
    },
    {
     "title": "Inode Stats For ${fs} on ${hostname}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "statfs_files{instance=~\"${instance}\",hostname=\"${hostname}\",fs=~\"${fs}\"}",
       "legendFormat": "total(fs={{fs}},mnt={{mount_point}},host={{hostname}},inst={{instance}})"
      },
      {
       "expr": "statfs_ffree{instance=~\"${instance}\",hostname=\"${hostname}\",fs=~\"${fs}\"}",
       "legendFormat": "free(fs={{fs}},mnt={{mount_point}},host={{hostname}},inst={{instance}})"
      }
     ]
    }
   ]
  }
 ]
}