#! /usr/bin/env python3


# Mountinfo index definitions, matching procfs/mountinfo_parser.go

MOUNTINFO_MOUNT_ID = 0
MOUNTINFO_PARENT_ID = 1
MOUNTINFO_MAJOR_MINOR = 2
MOUNTINFO_ROOT = 3
MOUNTINFO_MOUNT_POINT = 4
MOUNTINFO_MOUNT_OPTIONS = 5
MOUNTINFO_OPTIONAL_FIELDS = 6
MOUNTINFO_OPTIONAL_FIELDS_SEPARATOR = 7
MOUNTINFO_FS_TYPE = 8
MOUNTINFO_MOUNT_SOURCE = 9
MOUNTINFO_SUPER_OPTIONS = 10

MOUNTINFO_NUM_FIELDS = 11
