{
 "title": "proc_net_snmp_metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "lsvmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "lsvmi_uptime_sec{instance=~\"${instance}\"}"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s" },
   { "name": "lookback", "query": "16s" },
   { "name": "data_threshold", "label": "Data Threshold", "query": "0" },
   { "name": "err_threshold", "label": "Error Threshold", "query": "0" }
  ]
 },
 "panels": [
  {
   "title": "IP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "IpIn Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_ip_in_receives_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_in_hdr_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_in_addr_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_forw_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_in_unknown_protos_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_in_discards_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_in_delivers_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "IpOut Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_ip_out_requests_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_out_discards_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_out_discards_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Ip Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_ip_reasm_timeout{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_reasm_reqds_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_reasm_oks_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_reasm_fails_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_frag_oks_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_frag_fails_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_ip_frag_creates_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "IpForwarding",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_ip_forwarding{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "IpDefaultTTL",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 11, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_ip_default_ttl{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "IcmpIn Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_icmp_in_msgs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_csum_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_dest_unreachs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_time_excds_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_parm_probs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_src_quenchs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_redirects_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_echos_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_echo_reps_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_timestamps_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_timestamp_reps_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_addr_masks_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_addr_mask_reps_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmpmsg_in_type3_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "IcmpOut Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_icmp_out_msgs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_dest_unreachs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_time_excds_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_parm_probs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_src_quenchs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_in_src_quenchs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_redirects_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_echos_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_echo_reps_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_timestamps_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_timestamp_reps_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_addr_masks_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmp_out_addr_mask_reps_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_icmpmsg_out_type3_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "TcpIn Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_tcp_in_segs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_tcp_in_errs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_tcp_in_csum_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "TcpOut Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_tcp_out_segs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_tcp_out_rsts_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Tcp Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_tcp_active_opens_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_tcp_passive_opens_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_tcp_attempt_fails_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_tcp_estab_resets_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_tcp_retrans_segs_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "TcpRto",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_tcp_rto_algorithm{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_tcp_rto_min{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_tcp_rto_max{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "TcpEstablished",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 13, "x": 9, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_tcp_curr_estab{instance=~\"${instance}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "UdpIn Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_udp_in_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udp_in_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udp_rcvbuf_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udp_ignored_multi_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udp_in_csum_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "UdpOut Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_udp_out_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udp_sndbuf_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Udp Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_udp_no_ports_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udp_mem_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "UDPLite",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "UdpliteIn Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_udplite_in_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udplite_in_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udplite_rcvbuf_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udplite_ignored_multi_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udplite_in_csum_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"}  >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "UdpliteOut Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_udplite_out_datagrams_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udplite_sndbuf_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    },
    {
     "title": "Udplite Deltas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "proc_net_snmp_udplite_no_ports_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${data_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      },
      {
       "expr": "proc_net_snmp_udplite_mem_errors_delta{instance=~\"${instance}\",hostname=~\"${hostname}\"} >= ${err_threshold}",
       "legendFormat": "{{__name__}}({{instance}}/{{hostname}})"
      }
     ]
    }
   ]
  }
 ]
}