#! /bin/bash --noprofile

case "$0" in
    /*|*/*) 
        this_dir=$(cd $(dirname $0) && pwd)
    ;;
    *) 
        this_dir=$(cd $(dirname $(which $0)) && pwd)
    ;;
esac

set -e
(set -x; $this_dir/../dev/build-image)

while read os arch platform; do
    if [[ "$os" = '#'* || -z "$os" || -z "$arch"  || -z "$platform" ]]; then
        continue
    fi
    bin_dir=../../../../bin/$os-$arch
    files_dir=../../files
    (
        set -x
        cd $this_dir
        mkdir -p staging/$platform/lsvmi
        rsync -plrtHSv --exclude=bin/ --exclude=out/ --exclude=log/ $files_dir/lsvmi/ staging/$platform/lsvmi
        mkdir -p staging/$platform/lsvmi/bin
        rsync -plrtHSLv $bin_dir/ staging/$platform/lsvmi/bin
    )
done < platforms

